### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by Shiva108** [improsec/ImprosecPasswordAuditor#2]
When loading project in VS2019 a retarget suggestion pops up:
![image](https://user-images.githubusercontent.com/13223532/149911856-eddfc420-cfe1-4996-982d-95b648a750e1.png)
Continuing with "CANCEL" and then build/debug gives compiler errors:
![image](https://user-images.githubusercontent.com/13223532/149912051-467a9181-6416-4408-8f04-d2e4687debd6.png)
Continuing with "OK" and then build/debug also gives compiler errors:
![image](https://user-images.githubusercontent.com/13223532/149912857-8ee1020e-03a2-4ef5-931f-f81ee8140fc4.png)

Please advice.

**Comment by ghost** [comment]
Hello Shiva,

In order to compile the DSInternals.Replication.Interop module, make sure you update the Windows SDK version to a version that exists on your system as shown below.

![image](https://user-images.githubusercontent.com/79981713/159680703-9cb3b0b7-46ad-4114-b3e0-b14b0c3abfa3.png)

Then right-click the solution and click "Rebuild" as shown below.

![image](https://user-images.githubusercontent.com/79981713/159680858-26775696-d353-4628-9960-fad7485fe89a.png)

This should allow the the DSInternals modules to build.

For the "ipscan" errors, I can see that the linker somehow cached some includes on my end, that didn't transfer to GitHub, so I've updated the "hash_scanner.cpp" file to include headers that fixes these issues.

Lastly, put the solution in x64 compilation mode and it should work out of the box now :)

**Comment by Shiva108** [comment]
Cheers!
